version: '3.8'
services:

  db_m:
    build: ./master
    # restart: always
    volumes:
      - ./:/app
      - ./master:/db_conf
      - ./master/data:/var/lib/postgresql/data
      - ./db_configure.sh:/docker-entrypoint-initdb.d/db_configure.sh

    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 127.0.0.1:${DB_LOCAL_PORT_M}:5432

  db_s:
    build: ./slave
    # restart: always
    volumes:
      - ./:/app
      - ./slave:/db_conf
      - ./slave/data:/var/lib/postgresql/data
      - ./db_configure.sh:/docker-entrypoint-initdb.d/db_configure.sh
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 127.0.0.1:${DB_LOCAL_PORT_S}:5432
    depends_on:
      - db_m
