version: '3.8'
services:
  db-master:
    image: docker.io/bitnami/postgresql:12
    ports:
      - '5432'
    volumes:
      - db_master_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=${DB_REPL_USER}
      - POSTGRESQL_REPLICATION_PASSWORD=${DB_REPL_PASSWORD}
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
      - ALLOW_EMPTY_PASSWORD=yes

  db-slave:
    image: docker.io/bitnami/postgresql:12
    ports:
      - '5432'
    depends_on:
      - db-master
    volumes:
      - db_slave_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=${DB_REPL_USER}
      - POSTGRESQL_REPLICATION_PASSWORD=${DB_REPL_PASSWORD}
      - POSTGRESQL_MASTER_HOST=db-master
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  db_master_data:
    driver: local
  db_slave_data:
    driver: local
